
services:
  scylla:
    image: scylladb/scylla:latest
    container_name: urlshortener-scylla
    ports:
      - "9042:9042"
    command: --smp 1 --memory 1G

  redis:
    image: redis/redis-stack-server:latest
    container_name: urlshortener-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: zookeeper:latest
    container_name: urlshortener-zookeeper
    ports:
      - "2181:2181"

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: urlshortener-redpanda
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://127.0.0.1:19092
    ports:
      - "19092:19092"
      - "9092:9092"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: urlshortener-clickhouse
    ports:
      - "8123:8123"
      - "19000:9000"
    environment:
      - CLICKHOUSE_PASSWORD=password
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
